version: 2
project_name: alror

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: alror
    main: ./cmd/alror
    binary: alror
    env: [CGO_ENABLED=0]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X github.com/manaskumar3003/alror-cli/internal/cli.Version={{ .Version }}
  - id: alror-docs
    main: ./cmd/alror-docs
    binary: alror-docs
    env: [CGO_ENABLED=0]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags: [-s -w]

archives:
  - id: default
    ids: [alror, alror-docs]
    name_template: "alror_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    files: [LICENSE, README.md]

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude: ["^docs:", "^test:", "^chore:"]

release:
  github:
    owner: manaskumar3003
    name: alror-cli
